//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCalaisExample.Calais {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://clearforest.com/", ConfigurationName="Calais.calaisSoap")]
    public interface calaisSoap {
        
        // CODEGEN: Generating message contract since element name licenseID from namespace http://clearforest.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://clearforest.com/Enlighten", ReplyAction="*")]
        OpenCalaisExample.Calais.EnlightenResponse Enlighten(OpenCalaisExample.Calais.EnlightenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clearforest.com/Enlighten", ReplyAction="*")]
        System.Threading.Tasks.Task<OpenCalaisExample.Calais.EnlightenResponse> EnlightenAsync(OpenCalaisExample.Calais.EnlightenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnlightenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enlighten", Namespace="http://clearforest.com/", Order=0)]
        public OpenCalaisExample.Calais.EnlightenRequestBody Body;
        
        public EnlightenRequest() {
        }
        
        public EnlightenRequest(OpenCalaisExample.Calais.EnlightenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://clearforest.com/")]
    public partial class EnlightenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string licenseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string paramsXML;
        
        public EnlightenRequestBody() {
        }
        
        public EnlightenRequestBody(string licenseID, string content, string paramsXML) {
            this.licenseID = licenseID;
            this.content = content;
            this.paramsXML = paramsXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnlightenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnlightenResponse", Namespace="http://clearforest.com/", Order=0)]
        public OpenCalaisExample.Calais.EnlightenResponseBody Body;
        
        public EnlightenResponse() {
        }
        
        public EnlightenResponse(OpenCalaisExample.Calais.EnlightenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://clearforest.com/")]
    public partial class EnlightenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnlightenResult;
        
        public EnlightenResponseBody() {
        }
        
        public EnlightenResponseBody(string EnlightenResult) {
            this.EnlightenResult = EnlightenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calaisSoapChannel : OpenCalaisExample.Calais.calaisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calaisSoapClient : System.ServiceModel.ClientBase<OpenCalaisExample.Calais.calaisSoap>, OpenCalaisExample.Calais.calaisSoap {
        
        public calaisSoapClient() {
        }
        
        public calaisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calaisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calaisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calaisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OpenCalaisExample.Calais.EnlightenResponse OpenCalaisExample.Calais.calaisSoap.Enlighten(OpenCalaisExample.Calais.EnlightenRequest request) {
            return base.Channel.Enlighten(request);
        }
        
        public string Enlighten(string licenseID, string content, string paramsXML) {
            OpenCalaisExample.Calais.EnlightenRequest inValue = new OpenCalaisExample.Calais.EnlightenRequest();
            inValue.Body = new OpenCalaisExample.Calais.EnlightenRequestBody();
            inValue.Body.licenseID = licenseID;
            inValue.Body.content = content;
            inValue.Body.paramsXML = paramsXML;
            OpenCalaisExample.Calais.EnlightenResponse retVal = ((OpenCalaisExample.Calais.calaisSoap)(this)).Enlighten(inValue);
            return retVal.Body.EnlightenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenCalaisExample.Calais.EnlightenResponse> OpenCalaisExample.Calais.calaisSoap.EnlightenAsync(OpenCalaisExample.Calais.EnlightenRequest request) {
            return base.Channel.EnlightenAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenCalaisExample.Calais.EnlightenResponse> EnlightenAsync(string licenseID, string content, string paramsXML) {
            OpenCalaisExample.Calais.EnlightenRequest inValue = new OpenCalaisExample.Calais.EnlightenRequest();
            inValue.Body = new OpenCalaisExample.Calais.EnlightenRequestBody();
            inValue.Body.licenseID = licenseID;
            inValue.Body.content = content;
            inValue.Body.paramsXML = paramsXML;
            return ((OpenCalaisExample.Calais.calaisSoap)(this)).EnlightenAsync(inValue);
        }
    }
}
